add resources for users, profiles, operator accounts and sms account
sebz/airvantage.js pull request #12
Opened 2016-10-11 15:00 UTC by mbarrailh

2016-10-13 15:24 UTC, sebz requested changes

2016-10-13 15:24 UTC, sebz commented on .jshintrc
> +    esversion": 6
I have another branch for the switch to ES6, can you remove this property?

2016-10-13 15:24 UTC, sebz commented on lib/airvantage.js
> +"use strict";
Should not be required in ES5.

2016-10-17 13:09 UTC, jlescot commented on .jshintrc
> -    // Documentation: http://www.jshint.com/docs/
I guess we might keep these comments...

2016-10-17 13:10 UTC, jlescot commented on lib/airvantage.js
> +}
⚠️ Code formatter used to add a blank line at the end of the file...

2017-02-07 12:51 UTC, merged